[package]
name = "swirl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "*"
glob = "0.3.0"
iced = { version = "0.6.0", features = ["svg"] }
iced_native = "0.6.1"
once_cell = "1.16.0"
